<script>
	var car = {};

	Object.defineProperty(car, 'doors', {
		writable: true,
		configurable: true,
		enumerable: true,
		value: 4
	});

	Object.defineProperty(car, 'wheels', {
		writable: true,
		configurable: true,
		enumerable: true,
		value: 4
	});

	Object.defineProperty(car, 'secretTrackingDeviceEnabled', {
		enumerable: false,
		value: true
	});

	for (var x in car) {
		console.log(x);
	}

	console.log(Object.keys(car));

	console.log(Object.getOwnPropertyNames(car));

	console.log(car.propertyIsEnumerable('secretTrackingDeviceEnabled'));

	console.log(car.secretTrackingDeviceEnabled);
</script>