<script>
	var Dog = function() {};

	Dog.prototype.speak = function() {
		return "woof";
	}; 

	var Cat = function() {};

	Cat.prototype.speak = function() {
		return "meow";
	};

	var Tabby = function() {};

	Tabby.prototype = new Cat();
	var tabbyCat = new Tabby();

	console.log(tabbyCat.speak());

	console.log(tabbyCat.prototype);

	tabbyCat.prototype = new Dog();

	console.log(tabbyCat.prototype);

	console.log(tabbyCat.speak());
</script>